AWSTemplateFormatVersion: "2010-09-09"
Description: Role for Botmetric Managed/Automation Access. https://github.com/peeweeh/cf-basics
Resources:
  BotmetricManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Description: "Policy for allowing Botmetric to Read AWS Resources"
    Properties: 
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "ec2:CreateSnapshot"
              - "ec2:DeleteSnapshot"
              - "ec2:DeleteVolume"
              - "ec2:CreateTags"
              - "ec2:DeleteKeyPair"
              - "ec2:ModifyInstanceAttribute"
              - "ec2:ReleaseAddress"
              - "ec2:Describe*"
              - "ec2:StartInstances"
              - "ec2:StopInstances"
              - "ec2:RegisterImage"
              - "ec2:DeregisterImage"
              - "ec2:CreateImage"
              - "ec2:CopySnapshot"
              - "ec2:DisassociateAddress"
              - "ec2:DeleteSecurityGroup"
              - "ec2:CopyImage"
              - "ec2:TerminateInstances"
              - "ec2:ModifySnapshotAttribute"
              - "s3:CreateBucket"
              - "s3:ListBucket"
              - "s3:PutObject"
              - "cloudtrail:CreateTrail"
              - "cloudtrail:StartLogging"
              - "cloudtrail:UpdateTrail"
              - "rds:DescribeDBInstances"
              - "rds:DescribeDBSnapshots"
              - "rds:ListTagsForResource"
              - "rds:CreateDBSnapshot"
              - "rds:DeleteDBSnapshot"
              - "rds:ModifyDBInstance"
              - "rds:CopyDBSnapshot"
              - "rds:DeleteDBInstance"
              - "iam:ListRolePolicies"
              - "iam:GetRolePolicy"
              - "iam:GetRole"
              - "iam:GetPolicy"
              - "iam:GetPolicyVersion"
              - "iam:ListAttachedRolePolicies"
              - "iam:DeleteAccessKey"
              - "iam:UpdateAccountPasswordPolicy"
              - "iam:GetAccountPasswordPolicy"
              - "iam:UpdateAccountPasswordPolicy"
              - "iam:ListAccessKeys"
              - "iam:GetAccessKeyLastUsed"
              - "autoscaling:DescribeAutoScalingGroups"
              - "autoscaling:UpdateAutoScalingGroup"
              - "autoscaling:SetDesiredCapacity"
              - "redshift:CreateClusterSnapshot"
              - "redshift:DeleteClusterSnapshot"
              - "redshift:DescribeClusterSnapshots"
              - "redshift:DescribeClusters"
              - "elasticloadbalancing:DeleteLoadBalancer"
              - "elasticloadbalancing:ModifyLoadBalancerAttributes"
              - "elasticloadbalancing:DescribeLoadBalancers"
              - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"  
            Resource: "*"