AWSTemplateFormatVersion: "2010-09-09"
Description: Allows EC2 Instances to Download SSH Keys from IAM for Authentication. https://github.com/peeweeh/cf-basics
Resources:
  SSHIAMPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties: 
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "iam:ListUsers"
              - "iam:ListSSHPublicKeys"
              - "iam:GetSSHPublicKey"
            Resource: "*"
